apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: nginx
    command: ["sleep"]
    args: ["30"]
  restartPolicy: OnFailure
