apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-probe-http
spec:
  containers:
  - name: liveness-probe-http
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
