apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-probe-exec
spec:
  containers:
  - name: liveness-probe-exec
    image: nginx 
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5