apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-probe-tcp
spec:
  containers:
  - name: liveness-probe-tcp
    image: nginx 
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
