apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: oidc-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oidc-role
subjects:
- kind: ServiceAccount
  name: oidc-service-account
  namespace: default
