apiVersion: v1
kind: Pod
metadata:
  labels:
    run: awscli
  name: oidc-awscli
spec:
  serviceAccountName: oidc-service-account  
  containers:
  - image: amazon/aws-cli
    name: oidc-awscli
    command: ["sleep","600"]
    