
apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod 
spec:
  containers:
    - name: pvc-pod 
      image: nginx 
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: persistent-volume-claim