
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: abcd 
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi