apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe-http
  labels: 
    region: test
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080        
      initialDelaySeconds: 3
      periodSeconds: 3    