apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe-tcp
  labels: 
    region: test
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10