
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-pass-key 
spec:
  containers:
  - name: secret-pod-pass-key
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
