
# This is to create a secret in declarative way. Data should given in base64 encoded form using echo -n 'value' | base64
# To decode use echo -n 'value' | base64 --decode

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: c3VwZXJwYXNzd29yZA==