
# This is to pass the whole secret value to pod. 

apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-whole 
spec:
  containers:
    - name: secret-pod-whole 
      image: nginx 
      envFrom:
      - secretRef:
          name: mysecret
