
# Service account token can be referred as volume in pod. 

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  serviceAccountName: test-service-account
  containers:
  - image: nginx
    name: nginx
    