
apiVersion: v1
kind: Pod
metadata:
  name: volumes
spec:
  containers:
  - image: nginx 
    name: nginx 
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /
      # this field is optional
      type: Directory